### ISSUE TITLE
Erron on initialization (pyo3_runtime.PanicException)

### ISSUE THREAD

**Issue by TomaszKot2** [Congyuwang/Py-Bitcoin-Explorer#1]
I get following error during initialization (Python 3.8.11).

import bitcoin_explorer as bex
db = bex.BitcoinDB(r"D:\BTC\Chain")

[19:02:59] INFO - Start loading block_index
[19:03:00] INFO - Longest chain: 702696
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 58, error_len: Some(1) }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\leveldb-0.8.6\src\database\error.rs:29:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:/Users/T/PycharmProjects/BTC_explorer/main.py", line 3, in <module>
    db = bex.BitcoinDB(r"D:\BTC\Chain")
  File "D:\anaconda3\envs\env_btc\lib\site-packages\bitcoin_explorer\__init__.py", line 82, in __init__
    self.db = _BitcoinDB(str(path), tx_index)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 58, error_len: Some(1) }
Process finished with exit code 1

I have data downloaded using Bitcoin Core in D:\BTC\Chain\blocks (.dat files) and D:\BTC\Chain\blocks\index (.ldb files).

**Comment by Congyuwang** [comment]
I guess it is related to windows system address. Let me test it. Thank you for reporting.

**Comment by Congyuwang** [comment]
Could you please try `db = bex.BitcoinDB(r"D:\BTC\Chain", tx_index=False)`. This issue is a problem opening the tx_index in `D:\BTC\Chain\index` (maybe this folder does not exist).

**Comment by Congyuwang** [comment]
The `levelDB` rust package fails to decode levelDB error message, and thus UTF-8 decoding error, and it simply panicked. I should create a pull request to `levelDB` crate.

**Comment by Congyuwang** [comment]
I've added a check to check whether tx_index folder exists, which might have solved the issue.

Could you try version v1.0.5 `pip install bitcoin_explorer==1.0.5`? `db = bex.BitcoinDB(r"D:\BTC\Chain")`.

**Comment by TomaszKot2** [comment]
Thank you for your reply. I have installed v.1.0.5.
Now with db = bex.BitcoinDB(r"D:\BTC\Chain") I get following error:
[09:05:35] INFO - Start loading block_index
[09:05:35] INFO - Longest chain: 702696
[09:05:37] WARNING - Failed to open tx_index DB: tx_index not built

Please note that index folder is located (automatically on my system) in:
D:\BTC\Chain\blocks\index
not in D:\BTC\Chain\index
I thought that maybe it causes the problem, but moving the index folder didn't also fix it.

**Comment by TomaszKot2** [comment]
Hi Congyuwang,

Thank you, I have installed 1.0.5 and described the results on GitHub
(still getting the error unfortunately).

I would also like to ask you a technical question.
I need to export all transactions to csv file (or files).
I will need to parse:
"address from",
"address(es) to",
"btc amount(s)"
and also an additional column that gives the possibility to further map it
with date of operation.

I thought about db.get_transaction("txid"), but I can see in the
documentation that it would be slow.
How can I export all the transactions with the above data in the most
efficient way?
If it takes a few hours (or even several) it will still be ok.

Best wishes,
Tomasz




pon., 4 paź 2021 o 02:33 Congyu ***@***.***> napisał(a):

**Comment by Congyuwang** [comment]
You can safely ignore this warning.

```
[09:05:35] INFO - Start loading block_index
[09:05:35] INFO - Longest chain: 702696
[09:05:37] WARNING - Failed to open tx_index DB: tx_index not built
```

Use the following if you want efficient deserialization of `addresses to addresses, value` information

```
for block in db.get_block_iter_range(end=700000, connected=True):
    do_something_with(block)
```

**Comment by Congyuwang** [comment]
These are block index: `D:\BTC\Chain\blocks\index`
These are transaction index `D:\BTC\Chain\index`, which is not needed for `db.get_block_iter_range(end=700000, connected=True)`

**Comment by TomaszKot2** [comment]
With code:
import bitcoin_explorer as bex
db = bex.BitcoinDB(r"D:\BTC\Chain")
db.get_transaction("97d1b00fcef1f19531a19bb1722635341a9f2ad261ecf6eed89eca2cbd3bb3ee")

I get:
[08:16:41] INFO - Start loading block_index
[08:16:41] INFO - Longest chain: 702696
[08:16:43] WARNING - Failed to open tx_index DB: tx_index not built
Traceback (most recent call last):
  File "C:/Users/F/PycharmProjects/BTC_explorer/main.py", line 3, in <module>
    db.get_transaction("97d1b00fcef1f19531a19bb1722635341a9f2ad261ecf6eed89eca2cbd3bb3ee")
  File "D:\anaconda3\envs\env_btc\lib\site-packages\bitcoin_explorer\__init__.py", line 218, in get_transaction
    return self.db.get_transaction_simple(txid)
Exception: TxDB not open

**Comment by TomaszKot2** [comment]
Could you give a hint how to use: 
for block in db.get_block_iter_range(end=700000, connected=True)
to extract all btc transactions data from iterated block (addresses to addresses, value, timestamp)?

**Comment by Congyuwang** [comment]
If you haven't launched Bitcoin Core with --txindex=1 (before downloading all blockchain), you won't be able to use `db.get_transaction("97d1b00fcef1f19531a19bb1722635341a9f2ad261ecf6eed89eca2cbd3bb3ee")`.

**Comment by Congyuwang** [comment]
`get_transaction` is slow any way. To use iterator instead, check the object block first.

For example, see the structure of block 500
```python
count = 0
for block in db.get_block_iter_range(end=700000, connected=True):
    if count == 500:
        break
    block += 1

print(block)
```

**Comment by Congyuwang** [comment]
Try this:

`pip install bitcoin_explorer==1.0.9` (new version requires less memory (minimal requirement: 32GB memory) for `db.get_block_iter_range(connected=True)`)

```python
import bitcoin_explorer as bex
from tqdm import tqdm

db = bex.BitcoinDB("./bitcoin")

for block in tqdm(db.get_block_iter_range(stop=700000, connected=True), total=700000):
    for transaction in block["txdata"]:
        # list of addresses and values of senders
        inputs = transaction["input"]
        # list of addresses and values of recievers
        outputs = transaction["output"]
```

**Comment by Congyuwang** [comment]
One block has multiple transactions. One transaction has multiple inputs and outputs. (Coinbase transactions do not have inputs). Each input and output usually have one address (or no address if non-standard, or multiple addresses if multisig script).

**Comment by TomaszKot2** [comment]
Ok, thank you.
I started to parse transactions yesterday (using 1.0.5). It seems that it
will take a few days. I have 64GB RAM.
Is 1.0.9 much faster (is it worth it to stop the process and restart again
using 1.0.9?)
Sometimes in the output there is one value and many addresses (multisig) -
is there a way to know which part of value was transferred to each address?

śr., 6 paź 2021 o 07:41 Congyu ***@***.***> napisał(a):

**Comment by Congyuwang** [comment]
1.0.9 is faster,  but there is no need to restart this. Using Rust directly would be much faster if you find python too slow.

Multisig shares the ownership of the value (e.g., 2-3-multisig requires two of the three private keys to spend the coins).
